spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/one_stop_shop
    username: root
    password: root
  sql:
    init:
      mode: always
  flyway:
    baseline-on-migrate: true
logging:
  level:
    sql: DEBUG
